# Generated by Django 5.2 on 2025-04-18 01:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Destino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('direccion', models.CharField(blank=True, max_length=200)),
                ('contacto', models.CharField(blank=True, max_length=100)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Lote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('fecha_caducidad', models.DateField()),
                ('fecha_recepcion', models.DateField()),
                ('ubicacion', models.CharField(max_length=100)),
                ('fecha_captura', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('unidad_medida', models.CharField(max_length=50)),
                ('codigo_barras', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('direccion', models.CharField(blank=True, max_length=200)),
                ('contacto', models.CharField(blank=True, max_length=100)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('login', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('rol', models.CharField(choices=[('Gerente', 'Gerente'), ('Almacen', 'Almacén')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Donacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_donacion', models.DateTimeField()),
                ('comentario', models.TextField(blank=True)),
                ('estado', models.CharField(choices=[('Autorizado', 'Autorizado'), ('Pendiente', 'Pendiente'), ('Enviado', 'Enviado')], max_length=20)),
                ('destino', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='lotes.destino')),
                ('usuario_autoriza', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='lotes.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='DonacionDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('donacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lotes.donacion')),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='lotes.lote')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='lotes.producto')),
            ],
        ),
        migrations.AddField(
            model_name='lote',
            name='proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='lotes.proveedor'),
        ),
        migrations.CreateModel(
            name='LoteDet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('fecha_captura', models.DateTimeField(auto_now_add=True)),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lotes.lote')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='lotes.producto')),
                ('usuario_captura', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='lotes.usuario')),
            ],
        ),
        migrations.AddField(
            model_name='lote',
            name='usuario_captura',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='lotes.usuario'),
        ),
    ]
